### ISSUE TITLE
Any plan to put on chrome web store?

### ISSUE THREAD

**Issue by tonytonyjan** [whiteswift/pomodoro-pwa#1]
I really like your project, especially the design, it's very easy to use. Thank you for opening the source!

I wonder if there is any future plan of releasing to chrome web store?

**Comment by whiteswift** [comment]
Sorry for the late reply.

I don't have plans to release this to the Chrome web store sorry, however - as it's a progressive web app, you can add it to your app drawer on desktop or add to your home screen on android, and it will work offline like a native app 🌈🌈🌈🌈🌈.

**Comment by baamenabar** [comment]
that is exactly how I am using it: PWA FTW !

Best Pomodoro PWA out there, I tried the 2 others, I kept this one.  Thanks for this 👍
