### ISSUE TITLE
Add settings page and save logs in localstorage

### ISSUE THREAD

**Issue by JoseCage** [whiteswift/pomodoro-pwa#2]
I tested your app/pwa and I think would be very good if you add more features like "Let user change settings of **PWA** app, like (de)activate alarm/vibration",  and "save time log".

With "save time log" I mean, save in **local storage** every Pomodoro session. It may help the user to see their last work times or maybe compare how much time he is spending.

**Comment by whiteswift** [comment]
Hi Jose, sorry for the late reply, if you still want this I'll be happy to look at a pull request?

**Comment by JoseCage** [comment]
> Hi Jose, sorry for the late reply, if you still want this I'll be happy to look at a pull request?

Thanks for your feedback.

Sorry. For now I'm not using, so I don't know if I still can help.
